#!/bin/bash

DISK="/dev/sda"
VG="ubuntu-vg"

# Create PV, VG
sudo pvcreate $DISK
sudo vgcreate $VG $DISK

# Create LVs
sudo lvcreate -L 50G -n opt_dynatrace $VG
sudo lvcreate -L 100G -n var_dynatrace $VG
sudo lvcreate -L 50G -n cassandra $VG
sudo lvcreate -L 50G -n elasticsearch $VG

# Format
sudo mkfs.ext4 /dev/$VG/opt_dynatrace
sudo mkfs.ext4 /dev/$VG/var_dynatrace
sudo mkfs.ext4 /dev/$VG/cassandra
sudo mkfs.ext4 /dev/$VG/elasticsearch

# Create mount points
sudo mkdir -p /opt/dynatrace-managed
sudo mkdir -p /var/opt/dynatrace-managed/{cassandra,elasticsearch}
#sudo mkdir -p /var/opt/dynatrace-managed/cassandra
#sudo mkdir -p /var/opt/dynatrace-managed/elasticsearch

# Mount
echo "Updating /etc/fstab..."
echo "/dev/$VG/opt_dynatrace /opt/dynatrace-managed ext4 defaults 0 2" | sudo tee -a /etc/fstab
echo "/dev/$VG/var_dynatrace /var/opt/dynatrace-managed ext4 defaults 0 2" | sudo tee -a /etc/fstab
echo "/dev/$VG/cassandra /var/opt/dynatrace-managed/cassandra ext4 defaults 0 2" | sudo tee -a /etc/fstab
echo "/dev/$VG/elasticsearch /var/opt/dynatrace-managed/elasticsearch ext4 defaults 0 2" | sudo tee -a /etc/fstab

# Mount all
sudo mount -a
