#!/bin/bash
set -e

# Path to tmux config
CONF="$HOME/.tmux.conf"

# Create or overwrite with your config
cat > "$CONF" <<'EOF'
# --- Your tmux config below ---
#C-j adn C-f for the prefix.
set-option -g prefix C-j
set-option -g prefix2 C-f

# Easy config reload

bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf is reloaded & anas is awesome"

# Disable bell
set -g bell-action none

# Mouse Mode

set -g mouse on
#setw -g mode-keys vi
# synchronize all panes in a window
# don't use control S, too easily confused
# with navigation key sequences in tmux (show sessions)
unbind C-S
bind C-y set-window-option synchronize-panes

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v


#Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window



set -g status-interval 1
set -g status-right "#(pomo)"

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Auto-restore session on tmux start
set -g @continuum-restore 'on'

# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'


EOF

echo "✅ tmux configuration installed at $CONF"
