#!/usr/bin/env bash
set -e

current=$(hyprctl activeworkspace -j | jq '.id')
last=$(hyprctl workspaces -j | jq '.[] | select(.lastfocus == true) | .id')

# If last is valid and not the current workspace, go to it
if [[ -n "$last" && "$last" != "$current" ]]; then
  hyprctl dispatch workspace "$last"
else
  hyprctl dispatch workspace 1
fi
